# Generated by Django 4.0.2 on 2022-02-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0002_alter_products_image_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='image_id',
        ),
        migrations.AddField(
            model_name='products',
            name='image_id',
            field=models.ManyToManyField(blank=True, null=True, to='storeapp.Images', verbose_name='Image gallery'),
        ),
    ]
