# Generated by Django 4.0.2 on 2022-02-08 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0003_images_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baskets',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
