version: "3.5"

services:

  main_service:
    image: django_image
    volumes:
      - ./testStore:/testStore
    build: ./testStore
    env_file:
      - ./.env
    command: [ "python", "manage.py", "runserver", "0.0.0.0:8000" ]
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  postgres:
      container_name: postgres-prod
      image: postgres:13.0-alpine
      env_file:
        - ./.env
      ports:
        - "5432:5432"
